"""device claims

Revision ID: 6eb543e0a5d5
Revises: cdd5121db0b0
Create Date: 2026-08-19 09:52:51.658233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb543e0a5d5'
down_revision: Union[str, Sequence[str], None] = 'cdd5121db0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_claims_device_id'), 'device_claims', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_claims_username'), 'device_claims', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_claims_username'), table_name='device_claims')
    op.drop_index(op.f('ix_device_claims_device_id'), table_name='device_claims')
    op.drop_table('device_claims')
    # ### end Alembic commands ###
