"""canvas roster entries

Revision ID: cdd5121db0b0
Revises: 08b64221e00c
Create Date: 2026-08-13 16:41:45.103089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd5121db0b0'
down_revision: Union[str, Sequence[str], None] = '08b64221e00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('canvas_user_id', sa.Integer(), nullable=False),
    sa.Column('kthid', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_user_id', name='uq_roster_course_user')
    )
    op.create_index(op.f('ix_roster_entries_canvas_user_id'), 'roster_entries', ['canvas_user_id'], unique=False)
    op.create_index(op.f('ix_roster_entries_course_id'), 'roster_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_roster_entries_kthid'), 'roster_entries', ['kthid'], unique=False)
    op.create_index(op.f('ix_roster_entries_username'), 'roster_entries', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_entries_username'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_kthid'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_course_id'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_canvas_user_id'), table_name='roster_entries')
    op.drop_table('roster_entries')
    # ### end Alembic commands ###
