"""Reading course enrolments from Canvas.

Uses a personal access token generated by the teacher at
`<canvas>/profile/settings`, which needs no administrator: it is the one piece
of Canvas integration that is self-service. The token acts as that teacher, so
it is a secret — it is read from configuration and never logged or returned to
a client.

This module only *reads* enrolments. Nothing here authenticates a student.
"""

import logging
import re

import httpx

log = logging.getLogger("quizbinf")

# Canvas caps per_page at 100; anything larger is silently clamped.
PAGE_SIZE = 100
TIMEOUT = httpx.Timeout(20.0)


class CanvasError(Exception):
    """Canvas could not be reached, or refused the request."""


def _next_page(response: httpx.Response) -> str | None:
    """The `rel="next"` URL from Canvas's Link header, if there is one.

    Canvas paginates every list endpoint and does not report a total, so a
    course larger than one page is silently truncated unless the whole chain
    is followed. Link is the only way to know there is more.
    """
    link = response.headers.get("link") or response.headers.get("Link")
    if not link:
        return None
    for part in link.split(","):
        match = re.match(r'\s*<([^>]+)>\s*;\s*rel="next"', part)
        if match:
            return match.group(1)
    return None


def _get_all(url: str, token: str, params: dict | None = None) -> list[dict]:
    results: list[dict] = []
    headers = {"Authorization": f"Bearer {token}"}
    with httpx.Client(timeout=TIMEOUT, follow_redirects=True) as client:
        next_url: str | None = url
        first = True
        while next_url:
            try:
                response = client.get(
                    next_url, headers=headers, params=params if first else None
                )
            except httpx.HTTPError as exc:
                raise CanvasError(f"Could not reach Canvas: {exc}") from exc
            if response.status_code == 401:
                raise CanvasError(
                    "Canvas rejected the access token. Generate a new one under "
                    "Account → Settings → New Access Token."
                )
            if response.status_code == 404:
                raise CanvasError(
                    "Canvas has no such course, or the token's owner cannot see it."
                )
            if response.status_code >= 400:
                raise CanvasError(f"Canvas returned {response.status_code}")
            payload = response.json()
            if not isinstance(payload, list):
                raise CanvasError("Canvas returned an unexpected response")
            results.extend(payload)
            next_url = _next_page(response)
            first = False
            # A malformed Link chain must not loop forever.
            if len(results) > 20000:
                raise CanvasError("Refusing to page through more than 20000 records")
    return results


def username_from_login_id(login_id: str | None) -> str | None:
    """`"shiraza@kth.se"` -> `"shiraza"`, which is the KTH username.

    Returned as-is when there is no domain, since another Canvas install may
    use bare usernames as the login id.
    """
    if not login_id:
        return None
    return login_id.split("@", 1)[0].strip().lower() or None


def list_teacher_courses(base_url: str, token: str) -> list[dict]:
    """Courses the token's owner teaches, newest first, for picking one."""
    courses = _get_all(
        f"{base_url.rstrip('/')}/api/v1/courses",
        token,
        params={"enrollment_type": "teacher", "per_page": PAGE_SIZE, "state[]": "available"},
    )
    return [
        {"id": c["id"], "name": c.get("name") or f"Course {c['id']}", "code": c.get("course_code")}
        for c in courses
        if c.get("id") is not None
    ]


def list_course_students(base_url: str, token: str, course_id: int) -> list[dict]:
    """Students enrolled in a course, as identity records.

    Email is requested but not returned: the app never sends mail, so storing
    it would be personal data kept for no reason. Anyone without a usable
    login id is skipped rather than stored under a guessed username.
    """
    raw = _get_all(
        f"{base_url.rstrip('/')}/api/v1/courses/{course_id}/users",
        token,
        params={"enrollment_type[]": "student", "per_page": PAGE_SIZE},
    )

    students: list[dict] = []
    skipped = 0
    for user in raw:
        username = username_from_login_id(user.get("login_id"))
        if username is None or user.get("id") is None:
            skipped += 1
            continue
        students.append(
            {
                "canvas_user_id": int(user["id"]),
                "kthid": (user.get("sis_user_id") or None),
                "username": username,
                "display_name": user.get("name") or username,
            }
        )
    if skipped:
        log.warning("roster: skipped %d Canvas users without a login id", skipped)
    return students
