import logging
import os
import secrets
from functools import cached_property, lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

log = logging.getLogger("quizbinf")

# Placeholder that must never be used to sign real cookies.
DEV_SECRET = "dev-only-secret"


def _read_secret(path: Path) -> str | None:
    try:
        return path.read_text().strip() or None
    except FileNotFoundError:
        return None
    except OSError as exc:
        # Typically a file left by an earlier image that ran as another uid.
        log.error("cannot read the session secret at %s: %s", path, exc)
        return None


def _create_secret(path: Path) -> str | None:
    """Create the secret file, or adopt one another process created first.

    O_EXCL makes exactly one caller the creator. The obvious alternative —
    check whether the file exists, then write it — is wrong in two ways that
    both end in mismatched cookies: several callers starting together each
    generate their own and the last write wins, and a plain write truncates,
    so a concurrent reader sees an empty file and generates yet another.
    """
    generated = secrets.token_urlsafe(48)
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        # Lost the race, and that is fine: the winner's secret is the one
        # every other process will read.
        return _read_secret(path)
    except OSError as exc:
        log.error("cannot create a session secret at %s: %s", path, exc)
        return None
    with os.fdopen(fd, "w") as fh:
        fh.write(generated)
    return generated

# SciLifeLab Serve offers no way to set environment variables on an app, so
# settings are also read from a file on the mounted persistent volume. Upload
# `quizbinf.env` into the project storage to configure a Serve deployment.
VOLUME_ENV_FILE = "/home/data/quizbinf.env"


class Settings(BaseSettings):
    """All configuration comes from environment variables (12-factor).

    Sources, in increasing precedence: defaults < `/home/data/quizbinf.env`
    (for platforms without env-var support) < `.env` < real environment.

    Everything has a working default so the app boots on a platform that can
    only give us an image, a port and a mounted directory.
    """

    model_config = SettingsConfigDict(
        env_file=(VOLUME_ENV_FILE, ".env"), extra="ignore"
    )

    # Persistent storage. On Serve this is the project volume's mount path;
    # the database and the generated session secret live here.
    data_dir: str = "/home/data"

    # Unset means "derive from data_dir" (see resolved_database_url).
    database_url: str | None = None
    # Unset means "generate one and persist it" (see resolved_session_secret).
    session_secret: str | None = None
    # Unset means "derive from the incoming request" — see public_base.py.
    # Set it explicitly if the app is reached through a different hostname
    # than the one it sees.
    public_base_url: str | None = None

    # Comma-separated KTH usernames that get the teacher role.
    teacher_usernames: str = ""
    # Mock login must be explicitly enabled and is refused in production.
    mock_login: bool = False
    environment: str = "development"  # "development" | "production"

    # Roster-checked identification: a stop-gap for running the course before
    # a real identity provider is available. A student is *identified*, not
    # authenticated — they type a KTH address and are let in if it appears in
    # a synced roster. Teachers are the one privileged role, so they need a
    # shared password on top. Off unless deliberately switched on.
    roster_login: bool = False
    roster_teacher_password: str = ""

    # Canvas, for reading the course roster. The token is a personal access
    # token generated by the teacher at <canvas>/profile/settings — no admin
    # involved — and acts as that teacher, so it is a secret.
    canvas_base_url: str = "https://canvas.kth.se"
    canvas_token: str = ""

    # OIDC (login.kth.se) — unused until client registration with KTH IT.
    oidc_issuer: str = ""
    oidc_client_id: str = ""
    oidc_client_secret: str = ""

    @property
    def teachers(self) -> set[str]:
        return {u.strip() for u in self.teacher_usernames.split(",") if u.strip()}

    @property
    def mock_login_allowed(self) -> bool:
        return self.mock_login and self.environment != "production"

    @property
    def canvas_configured(self) -> bool:
        return bool(self.canvas_token and self.canvas_base_url)

    @property
    def roster_login_allowed(self) -> bool:
        """Roster login needs a teacher password to be usable at all.

        Without one there would be no way to reach the teacher views, and an
        empty configured password would let anyone on the roster claim to be
        a teacher by leaving the field blank.
        """
        return self.roster_login and bool(self.roster_teacher_password)

    def _writable_data_dir(self) -> Path | None:
        """The data directory, if we can actually write to it."""
        path = Path(self.data_dir)
        try:
            path.mkdir(parents=True, exist_ok=True)
            probe = path / ".write-test"
            probe.touch()
            probe.unlink()
            return path
        except OSError:
            return None

    @property
    def resolved_database_url(self) -> str:
        """Explicit setting, else SQLite on the persistent volume.

        Falling back to the working directory would put the database on the
        container's ephemeral filesystem, losing every answer on redeploy, so
        that is only used when no writable volume exists (e.g. local dev).
        """
        if self.database_url:
            return self.database_url
        data = self._writable_data_dir()
        if data is not None:
            db_file = data / "quizbinf.db"
            # An existing file may belong to another uid — e.g. written by an
            # earlier revision of this image that ran as root. SQLite would
            # fail on write and take the container down at the migration step,
            # so degrade to an ephemeral database instead of crash-looping.
            if not db_file.exists() or os.access(db_file, os.W_OK):
                return f"sqlite:///{db_file}"
        return "sqlite:///./quizbinf.db"

    @cached_property
    def resolved_session_secret(self) -> str:
        """Explicit setting, else a random secret persisted on the volume.

        The image is public, so a hardcoded default would let anyone forge a
        session cookie. Generating once and storing it next to the database
        keeps logins valid across restarts without any configuration.

        Cached, because every request verifies a cookie against this: as a
        plain property it was recomputed per request, so anything that made
        two evaluations disagree logged people out between one request and
        the next.
        """
        if self.session_secret and self.session_secret != DEV_SECRET:
            return self.session_secret
        data = self._writable_data_dir()
        if data is not None:
            secret_file = data / "session_secret"
            stored = _read_secret(secret_file) or _create_secret(secret_file)
            if stored:
                return stored
        if self.session_secret:
            return self.session_secret
        # Nothing readable and nothing writable. A per-process random secret
        # is safer than a known constant, but it rejects every cookie issued
        # by any other process — so say so rather than failing as a 401.
        log.error(
            "no session secret could be read or stored under %s: signing cookies "
            "with a per-process random value. Logins will break on restart and "
            "whenever more than one worker runs. Set SESSION_SECRET in %s.",
            self.data_dir,
            VOLUME_ENV_FILE,
        )
        return secrets.token_urlsafe(48)


@lru_cache
def get_settings() -> Settings:
    return Settings()
